# Generated by Django 4.0 on 2021-12-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eggs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outgoing',
            new_name='OutgoingEggStock',
        ),
        migrations.DeleteModel(
            name='TotalStock',
        ),
    ]
