# Generated by Django 4.0 on 2021-12-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0002_rename_outgoing_outgoingeggstock_delete_totalstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingeggstock',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='outgoingeggstock',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
