# Generated by Django 4.0 on 2021-12-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds13_outgoing',
            name='date',
            field=models.DateField(),
        ),
    ]
