# Generated by Django 4.0 on 2021-12-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_feeds13_outgoing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds13_incoming',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
