# Generated by Django 4.0 on 2021-12-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_feeds13_incoming_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds13_incoming',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
