# Generated by Django 4.0 on 2021-12-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('feed', '0005_feeds13_incoming_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedS16_Outgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f16_quantity', models.IntegerField(default=0)),
                ('f16_date', models.DateTimeField()),
                ('f16_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='FeedS16_Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f16_price', models.IntegerField(default=0)),
                ('f16_quantity', models.IntegerField(default=0)),
                ('f16_date', models.DateTimeField()),
                ('f16_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
    ]
